### ISSUE TITLE
ارسال نهایی

### ISSUE THREAD

**Issue by imanmalekian** [SharifAIChallenge/aic_site#298]
javaمن کد خودم رو وقتی ارسال میکنم بعد کامپایل ناموفق میزنه ، حتی کد اولیه خودتون رو هم که میفرستم ناموفق میزنه!!

**Comment by ali-bahjati** [comment]
لطفا الان مجددا بررسی کنید، ایا مشکل هنوز هم وجود داره؟

**Comment by hamidreza004** [comment]
I’m closing this issue because it has been inactive for a few days. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.
Please reopen if you still encounter this issue.

Thank you!
